DROP TABLE IF EXISTS cities;
CREATE TABLE IF NOT EXISTS cities(
    code                CHAR(3),
    name                TEXT,
    country_code        CHAR(2),
    timezone            TEXT,
    status              INT DEFAULT 1
);

INSERT INTO cities (code, name, country_code, timezone) VALUES
('ABJ', 'ABIDJAN', 'CI', 'Africa/Casablanca'),
('ABV', 'ABUJA', 'NG', 'Africa/Algiers'),
('ACC', 'ACCRA', 'GH', 'Africa/Casablanca'),
('ADB', 'IZMIR', 'TR', ''),
('ADD', 'ADDIS ABABA', 'ET', 'Africa/Djibouti'),
('ADE', 'ADEN', 'YE', 'Africa/Djibouti'),
('ADL', 'ADELAIDE', 'AU', ''),
('AGR', 'AGRA', 'IN', ''),
('AGX', 'AGATTI ISLAND', 'IN', ''),
('AJL', 'AIZAWL', 'IN', ''),
('AKL', 'AUCKLAND', 'NZ', ''),
('AKX', 'AKTOBE', 'KZ', 'Asia/Aqtobe'),
('ALA', 'ALMATY', 'KZ', 'Asia/Almaty'),
('ALH', 'ALBANY', 'AU', 'Asia/Chongqing'),
('AMD', 'AHMEDABAD', 'IN', ''),
('AMM', 'AMMAN', 'JO', 'Africa/Djibouti'),
('AMQ', 'AMBON', 'ID', 'Asia/Chongqing'),
('AMS', 'AMSTERDAM', 'NL', 'Africa/Cairo'),
('ANC', 'ANCHORAGE', 'US', 'America/Anchorage'),
('ANO', 'ANNOBON', 'GQ', 'Africa/Algiers'),
('ANR', 'ANTWERP', 'BE', 'Africa/Cairo'),
('AOJ', 'AOMORI', 'JP', ''),
('ARN', 'STOCKHOLM', 'SE', 'Africa/Algiers'),
('ASM', 'ASMARA', 'ER', ''),
('ATH', 'ATHENS', 'GR', 'Africa/Cairo'),
('ATQ', 'AMRITSAR', 'IN', ''),
('AUH', 'ABU DHABI', 'AE', ''),
('AVK', 'ARVAIKHEER', 'MN', 'Asia/Chongqing'),
('AWZ', 'AHWAZ', 'IR', 'Asia/Tehran'),
('AXD', 'ALEXANDROUPOLIS', 'GR', ''),
('AYQ', 'AYERS ROCK', 'AU', ''),
('AYT', 'ANTALYA', 'TR', 'Africa/Djibouti'),
('BAG', 'BAGUIO', 'PH', 'Asia/Chongqing'),
('BAH', 'MANAMA', 'BH', 'Africa/Djibouti'),
('BBI', 'BHUBANESWAR', 'IN', ''),
('BBO', 'BERBERA', 'SO', ''),
('BCD', 'BACOLOD', 'PH', 'Asia/Chongqing'),
('BCN', 'BARCELONA', 'ES', ''),
('BDO', 'BANDUNG', 'ID', 'Asia/Bangkok'),
('BDQ', 'VADODARA', 'IN', ''),
('BEK', 'BAREILLY', 'IN', ''),
('BEN', 'BENGHAZI', 'LY', ''),
('BEP', 'BELLARY', 'IN', ''),
('BER', 'BERLIN', 'DE', ''),
('BEY', 'BEIRUT', 'LB', 'Africa/Cairo'),
('BFN', 'BLOEMFOENTEIN', 'ZA', 'Africa/Cairo'),
('BGF', 'BAGUI', 'CF', 'Africa/Algiers'),
('BGR', 'BOGOR', 'ID', 'Asia/Bangkok'),
('BGW', 'BAGHDAD', 'IQ', 'Africa/Djibouti'),
('BHI', 'BHILAI', 'IN', ''),
('BHJ', 'BHUJ', 'IN', ''),
('BHO', 'BHOPAL', 'IN', ''),
('BHU', 'BHAVNAGAR', 'IN', ''),
('BIB', 'BAIDOA', 'SO', ''),
('BIK', 'BIAK', 'ID', 'Asia/Jayapura'),
('BKB', 'BIKANER', 'IN', ''),
('BKI', 'KOTA KINABALU', 'MY', ''),
('BKK', 'BANGKOK', 'TH', 'Asia/Bangkok'),
('BKO', 'BAMAKO', 'ML', 'Africa/Casablanca'),
('BLR', 'BENGALURU', 'IN', ''),
('BME', 'BROOME', 'AU', 'Asia/Chongqing'),
('BMP', 'BROMPTON ISLAND', 'AU', ''),
('BNE', 'BRISBANE', 'AU', ''),
('BNI', 'BENIN', 'NG', ''),
('BOM', 'MUMBAI', 'IN', ''),
('BPH', 'BISLIG CITY', 'PH', 'Asia/Chongqing'),
('BPM', 'BEGUMPET', 'IN', ''),
('BPN', 'BALIKPAPAN', 'ID', 'Asia/Bangkok'),
('BPS', 'PORTO SEGURO', 'BR', ''),
('BQA', 'BALER', 'PH', 'Asia/Chongqing'),
('BRU', 'BRUSSELS', 'BE', 'Africa/Cairo'),
('BSA', 'BOSSASO', 'SO', 'Africa/Djibouti'),
('BSB', 'BRASÍLIA', 'BE', ''),
('BSG', 'BATA', 'GQ', 'Africa/Algiers'),
('BSO', 'BASCO', 'PH', 'Asia/Chongqing'),
('BSR', 'BASRAH', 'IQ', ''),
('BTH', 'BATAM', 'ID', 'Asia/Bangkok'),
('BUA', 'BUKA', 'PG', 'Asia/Vladivostok'),
('BUD', 'BUDAPEST', 'HU', ''),
('BUG', 'BENGUELA', 'AO', 'Africa/Algiers'),
('BUH', 'BUCHAREST', 'RO', ''),
('BUO', 'BURAO', 'SO', 'Africa/Djibouti'),
('BUP', 'BATHINDA', 'IN', ''),
('BUS', 'BATUMI', 'GE', ''),
('BWN', 'BANDAR SERI BEGAWAN', 'BN', ''),
('BXJ', 'ALMATY', 'KZ', 'Asia/Almaty'),
('BXX', 'BORAMA', 'SO', 'Africa/Djibouti'),
('BYN', 'BAYANKHONGOR', 'MN', 'Asia/Chongqing'),
('BZV', 'BRAZZAVILLE', 'CG', 'Africa/Algiers'),
('CAB', 'CABINDA', 'AO', 'Africa/Algiers'),
('CAI', 'CAIRO', 'EG', 'Africa/Cairo'),
('CAN', 'GUANGZHOU', 'CN', ''),
('CAR', 'CAR NICOBAR', 'IN', ''),
('CBB', 'COCHABAMBA', 'BO', 'America/Araguaina'),
('CBD', 'CAR NICOBAR', 'IN', ''),
('CBM', 'MISSISSIPPI', 'US', ''),
('CBO', 'COTABATO', 'PH', 'Asia/Chongqing'),
('CBR', 'CANBERRA', 'AU', ''),
('CBT', 'CATUMBELA', 'AO', 'Africa/Algiers'),
('CCJ', 'CALICUT', 'IN', ''),
('CCU', 'KOLKATA', 'IN', ''),
('CDG', 'PARIS', 'FR', 'Africa/Algiers'),
('CEB', 'CEBU', 'PH', 'Asia/Chongqing'),
('CEI', 'CHIANG RAI', 'TH', ''),
('CFU', 'KERKYRA ISLAND', 'GR', ''),
('CGM', 'CAMIGUIN', 'PH', ''),
('CGO', 'ZHENGZHOU', 'CN', 'Asia/Chongqing'),
('CGY', 'CAGAYAN DE ORO', 'PH', 'Asia/Chongqing'),
('CHC', 'CHRISTCHURCH', 'NZ', ''),
('CHQ', 'SOUDA', 'GR', ''),
('CJB', 'COIMBATORE', 'IN', ''),
('CJJ', 'CHEONGJU', 'KR', 'Asia/Jayapura'),
('CJU', 'JEJU', 'KR', 'Asia/Jayapura'),
('CKG', 'CHONGQING', 'CN', 'Asia/Chongqing'),
('CKY', 'CONAKRY', 'GU', 'Africa/Algiers'),
('CMB', 'COLOMBO', 'LK', ''),
('CMN', 'CASABLANCA', 'MA', ''),
('CNF', 'CONFINS', 'BR', ''),
('CNN', 'KANNUR KERALA', 'IN', ''),
('CNS', 'CAIRNS', 'AU', 'Asia/Vladivostok'),
('CNX', 'CHIANG MAI', 'TH', 'Asia/Bangkok'),
('COH', 'COOCHBEHAR', 'IN', ''),
('COK', 'KOCHI', 'IN', ''),
('COO', 'COTONOU', 'BJ', 'Africa/Algiers'),
('COQ', 'CHOIBALSAN', 'MN', 'Asia/Chongqing'),
('COS', 'CORISCO', 'GQ', 'Africa/Algiers'),
('CPH', 'COPENHAGEN', 'DK', 'Africa/Algiers'),
('CPT', 'CAPE TOWN', 'ZA', 'Africa/Cairo'),
('CRK', 'ANGELES', 'PH', 'Asia/Chongqing'),
('CRL', 'BRUSSELS', 'BE', 'Africa/Cairo'),
('CRM', 'CATARMAN', 'PH', 'Asia/Chongqing'),
('CSX', 'CHANGSHA', 'CN', 'Asia/Chongqing'),
('CTS', 'CHITOSETOMAKOMAI', 'JP', ''),
('CTU', 'CHENGDU', 'CN', 'Asia/Chongqing'),
('CVQ', 'CARNARVON', 'AU', 'Asia/Chongqing'),
('CWB', 'CURITIBA', 'BR', ''),
('CXH', 'VANCOUVER', 'CA', 'America/Dawson'),
('CXR', 'NHA TRANG', 'VN', ''),
('CYP', 'CALBAYOG', 'PH', 'Asia/Chongqing'),
('CYZ', 'CAUAYAN', 'PH', 'Asia/Chongqing'),
('CZX', 'CHANGZHOU', 'CN', ''),
('DAC', 'DHAKA', 'BD', 'Asia/Almaty'),
('DAD', 'DA NANG', 'VN', ''),
('DAM', 'DAMASCUS', 'SY', 'Africa/Cairo'),
('DAR', 'DAR ES SALAAM', 'TZ', 'Africa/Djibouti'),
('DBR', 'BIHAR', 'IN', ''),
('DED', 'DEHRADUN', 'IN', ''),
('DEF', 'TRAINING2', 'ID', 'Asia/Bangkok'),
('DEL', 'NEW DELHI', 'IN', 'Asia/Calcutta'),
('DGH', 'DEOGHAR', 'IN', ''),
('DHM', 'DHARAMSHALA', 'IN', ''),
('DIB', 'DIBRUGARH', 'IN', ''),
('DIR', 'DIRE DAWA', 'ET', 'Africa/Djibouti'),
('DIU', 'DIU', 'IN', ''),
('DJB', 'JAMBI', 'ID', 'Asia/Bangkok'),
('DJJ', 'JAYAPURA', 'ID', 'Asia/Jayapura'),
('DKR', 'DAKAR', 'SN', 'Africa/Casablanca'),
('DLA', 'DOUALA', 'SN', 'Africa/Algiers'),
('DLC', 'DALIAN', 'CN', 'Asia/Chongqing'),
('DLZ', 'DALANZADGAD', 'MN', 'Asia/Chongqing'),
('DME', 'MOSKOW', 'RU', 'Africa/Djibouti'),
('DMK', 'DON MUANG', 'TH', 'Asia/Bangkok'),
('DMM', 'DAMMAM', 'SA', 'Africa/Djibouti'),
('DMU', 'DIMAPUR', 'IN', ''),
('DOH', 'DOHA', 'QA', 'Africa/Djibouti'),
('DPS', 'DENPASAR', 'ID', 'Asia/Chongqing'),
('DRW', 'DARWIN', 'AU', 'Australia/Darwin'),
('DTE', 'DAET', 'PH', 'Asia/Chongqing'),
('DUR', 'DURG', 'IN', ''),
('DUS', 'DUSSELDORF', 'DE', ''),
('DVO', 'DAVAO', 'PH', 'Asia/Chongqing'),
('DXB', 'DUBAI', 'AE', 'Asia/Aqtau'),
('DYG', 'DAYONG', 'CN', ''),
('DYU', 'DUSHANBE', 'TJ', 'Asia/Aqtobe'),
('EBB', 'ENTEBBE', 'UG', 'Africa/Djibouti'),
('EBL', 'ERBIL', 'IQ', 'Africa/Djibouti'),
('EFL', 'KEFALLINIA ISLAN', 'GR', ''),
('ENE', 'ENDE', 'ID', ''),
('ENI', 'ELNIDO PALAWAN', 'PH', ''),
('EPR', 'ESPERANCE', 'AU', 'Asia/Chongqing'),
('ERT', 'ERDENET', 'MN', 'Asia/Chongqing'),
('EUA', 'EUA', 'TO', 'Etc/GMT-13'),
('EUQ', 'ANTIQUE', 'PH', 'Asia/Chongqing'),
('EXM', 'EXMOUTH GULF', 'AU', 'Asia/Chongqing'),
('FCO', 'ROME', 'IT', 'Africa/Algiers'),
('FIH', 'KINSHASA', 'CD', 'Africa/Algiers'),
('FKS', 'FUKUSHIMA', 'JP', 'Asia/Jayapura'),
('FLN', 'FLORIANÓPOLIS', 'BR', ''),
('FLR', 'FLORENCE', 'IT', 'Africa/Algiers'),
('FOC', 'FUZHOU', 'CN', ''),
('FOR', 'FORTALEZA', 'BR', ''),
('FRA', 'FRANKFURT', 'DE', 'Africa/Algiers'),
('FRU', 'BISHKEK', 'KG', ''),
('FSZ', 'SHIZUOKA', 'JP', 'Asia/Jayapura'),
('FUK', 'FUKUOKA', 'JP', ''),
('GAJ', 'YAMAGATA', 'JP', 'Asia/Jayapura'),
('GAL', 'GALENA', 'US', 'America/Anchorage'),
('GAS', 'GARISSA', 'KE', ''),
('GAU', 'GUWAHATI', 'IN', ''),
('GAY', 'GAYA', 'IN', ''),
('GBI', 'KALABURAGI', 'IN', ''),
('GDB', 'GONDIA', 'IN', ''),
('GET', 'GERALDTON', 'AU', 'Asia/Chongqing'),
('GGN', 'GURGAON', 'IN', ''),
('GGR', 'GAROWE', 'SO', ''),
('GHI', 'TRAINING3', 'ID', 'Asia/Bangkok'),
('GHT', 'GHAT', 'LY', ''),
('GIG', 'RIO DE JANEIRO', 'BR', ''),
('GKA', 'GOROKA', 'PG', 'Asia/Vladivostok'),
('GLK', 'GALCAIO', 'SO', 'Africa/Djibouti'),
('GNS', 'GUNUNG SITOLI', 'ID', 'Asia/Bangkok'),
('GOI', 'GOA', 'IN', ''),
('GOP', 'GORAKHPUR', 'IN', ''),
('GOX', 'MOPA', 'IN', ''),
('GRU', 'GUARULHOS', 'BR', ''),
('GRV', 'GROZNYJ', 'RU', 'Asia/Aqtau'),
('GUM', 'GUAM', 'GU', 'Asia/Vladivostok'),
('GUR', 'ALOTAU', 'PG', ''),
('GUW', 'ATYRAU', 'KZ', 'Asia/Aqtobe'),
('GWL', 'GWALIOR', 'IN', ''),
('GXF', 'SEIYUN', 'YE', ''),
('HAH', 'HAHAYA', 'KM', ''),
('HAK', 'HAIKOU', 'CN', 'Asia/Chongqing'),
('HAN', 'HANOI', 'VN', 'Asia/Bangkok'),
('HBA', 'HOBART', 'AU', ''),
('HBE', 'ALEXANDRIA', 'EG', ''),
('HBX', 'HUBLI', 'IN', ''),
('HDQ', 'HDQ', 'ID', ''),
('HDY', 'HAT YAI', 'TH', 'Asia/Bangkok'),
('HEA', 'HERAT', 'AF', 'Asia/Kabul'),
('HEL', 'HELSINKI', 'FI', ''),
('HER', 'HERAKLION', 'GR', ''),
('HET', 'HOHHOT', 'CN', 'Asia/Chongqing'),
('HFE', 'HEFEI', 'CN', 'Asia/Chongqing'),
('HGA', 'HARGEISA', 'SO', 'Africa/Djibouti'),
('HGH', 'HANGZHOU', 'CN', 'Asia/Chongqing'),
('HGI', 'ITANAGAR', 'IN', ''),
('HGU', 'MOUNT HAGEN', 'PG', 'Asia/Vladivostok'),
('HIJ', 'HIROSHIMA', 'JP', 'Asia/Jayapura'),
('HJR', 'KHAJURAHO', 'IN', ''),
('HJT', 'KHUJIRT', 'MN', 'Asia/Chongqing'),
('HKG', 'HONGKONG', 'HK', 'Asia/Chongqing'),
('HKN', 'HOSKINS', 'PG', 'Asia/Vladivostok'),
('HKT', 'PHUKET', 'TH', 'Asia/Bangkok'),
('HNL', 'HONOLULU', 'US', ''),
('HOF', 'ALAHSA', 'SA', 'Africa/Djibouti'),
('HPA', 'HA APAI', 'TO', 'Etc/GMT-13'),
('HRB', 'HARBIN', 'CN', 'Asia/Chongqing'),
('HRE', 'HARARE', 'ZW', ''),
('HRG', 'HURGHADA', 'EG', ''),
('HRI', 'MATTALA', 'LK', ''),
('HSS', 'GURGAON HARYANA', 'IN', ''),
('HTM', 'KHATGAL', 'MN', 'Asia/Chongqing'),
('HVD', 'KHOVD', 'MN', 'Asia/Chongqing'),
('HYD', 'HYDERABAD', 'IN', ''),
('IAH', 'HOUSTON, TEXAS', 'US', ''),
('IAO', 'SIARGAO-SURIGAO', 'PH', 'Asia/Chongqing'),
('ICN', 'INCHEON', 'KR', 'Asia/Jayapura'),
('ICO', 'SICOGON ISLAND', 'PH', ''),
('IDR', 'INDORE', 'IN', ''),
('IEV', 'KIEV (KYIV)', 'UA', ''),
('IFN', 'ISFAHAN', 'IR', 'Asia/Tehran'),
('IGN', 'ILIGAN', 'PH', 'Asia/Chongqing'),
('IGU', 'FOZ DO IGUAÇU', 'BR', ''),
('IKT', 'IRKUTSK', 'RU', ''),
('IKU', 'TAMCHY', 'KG', 'Asia/Almaty'),
('ILO', 'ILOILO', 'PH', 'Asia/Chongqing'),
('IMF', 'IMPHAL', 'IN', ''),
('IOA', 'IOANNINA', 'GR', ''),
('IPH', 'IPOH', 'MY', 'Asia/Chongqing'),
('ISB', 'ISLAMABAD', 'PK', 'Asia/Aqtobe'),
('ISK', 'NASHIK', 'IN', ''),
('IST', 'ISTANBUL', 'TR', 'Africa/Cairo'),
('ISU', 'SULAIMANIYA', 'IQ', 'Africa/Algiers'),
('IUT', 'UTTARLAI', 'IN', ''),
('IXA', 'AGARTALA', 'IN', ''),
('IXB', 'SILIGURI', 'IN', ''),
('IXC', 'CHANDIGARH', 'IN', ''),
('IXD', 'PRAYAGRAJ', 'IN', ''),
('IXE', 'MANGALORE', 'IN', ''),
('IXG', 'BELAGAVI', 'IN', ''),
('IXH', 'KAILSHAHAR', 'IN', ''),
('IXI', 'LAKHIMPUR', 'IN', ''),
('IXJ', 'JAMMU', 'IN', ''),
('IXK', 'KESHOD', 'IN', ''),
('IXL', 'LEH', 'IN', ''),
('IXM', 'MADURAI', 'IN', ''),
('IXP', 'PATHANKOT', 'IN', ''),
('IXR', 'RANCHI', 'IN', ''),
('IXS', 'SILCHAR', 'IN', ''),
('IXT', 'PASIGHAT', 'IN', ''),
('IXU', 'AURANGABAD', 'IN', ''),
('IXW', 'JAMSHEDPUR', 'IN', ''),
('IXX', 'BIDAR', 'IN', ''),
('IXY', 'KANDLA', 'IN', ''),
('IXZ', 'ANDAMAN', 'IN', ''),
('IZO', 'IZUMO', 'JP', ''),
('JAF', 'JAFFNA', 'LK', ''),
('JAI', 'JAIPUR', 'IN', ''),
('JDH', 'JODHPUR', 'IN', ''),
('JED', 'JEDDAH', 'SA', 'Africa/Djibouti'),
('JGA', 'JAMNAGAR', 'IN', ''),
('JGB', 'JAGDALPUR', 'IN', ''),
('JIB', 'DJIBOUTI', 'DJ', 'Africa/Djibouti'),
('JJN', 'JINJIANG', 'CN', 'Asia/Chongqing'),
('JKH', 'CHIOS ISLAND', 'GR', ''),
('JKL', 'TRAINING4', 'ID', 'Asia/Bangkok'),
('JKT', 'JAKARTA', 'ID', 'Asia/Bangkok'),
('JLG', 'JALGAON', 'IN', ''),
('JLR', 'JABALPUR', 'IN', ''),
('JMK', 'MYKONOS ISLAND', 'GR', ''),
('JNB', 'JOHANNESBURG', 'ZA', 'Africa/Cairo'),
('JOL', 'JOLO', 'PH', 'Asia/Chongqing'),
('JRG', 'JHARSUGUDA', 'IN', ''),
('JRH', 'JORHAT', 'IN', ''),
('JRO', 'KILIMANJARO', 'TZ', 'Africa/Djibouti'),
('JSA', 'JAISALMER', 'IN', ''),
('JTR', 'SANTORINI ISLAND', 'GR', ''),
('JUB', 'JUBA', 'SS', ''),
('KAD', 'KADUNA', 'NG', ''),
('KAF', 'KARATO', 'PG', 'Asia/Vladivostok'),
('KAN', 'KANO', 'NG', ''),
('KAX', 'KALBARRI', 'AU', 'Asia/Chongqing'),
('KBK', 'KUSHINAGAR', 'IN', ''),
('KBL', 'KABUL', 'AF', 'Asia/Kabul'),
('KBR', 'KOTA BHARU', 'MY', ''),
('KBV', 'KRABI', 'TH', 'Asia/Bangkok'),
('KCH', 'KUCHING', 'MY', ''),
('KCZ', 'NANKOKU', 'JP', ''),
('KDH', 'KANDAHAR', 'AF', 'Asia/Kabul'),
('KDI', 'KENDARI', 'ID', 'Asia/Chongqing'),
('KGF', 'KARAGANDY', 'KZ', 'Asia/Almaty'),
('KGI', 'KALGOORLIE', 'AU', 'Asia/Chongqing'),
('KGS', 'KOS ISLAND', 'GR', ''),
('KHH', 'KAOHSIUNG CITY', 'TW', ''),
('KHI', 'KARACHI', 'PK', 'Asia/Aqtobe'),
('KHN', 'NANCHANG', 'CN', ''),
('KHR', 'KHARKHORIN', 'MN', 'Asia/Chongqing'),
('KIE', 'KIETA', 'PG', ''),
('KIH', 'KISH ISLAND', 'IR', 'Asia/Tehran'),
('KIJ', 'NIGATA', 'JP', 'Asia/Jayapura'),
('KIX', 'OSAKA KANSAI', 'JP', 'Asia/Jayapura'),
('KJA', 'KRASNOYARSK', 'RU', ''),
('KJB', 'KURNOOL', 'IN', ''),
('KKC', 'KHON KAEN', 'TH', ''),
('KKJ', 'KITA KYUSHU', 'JP', ''),
('KLH', 'KOLHAPUR', 'IN', ''),
('KLO', 'KALIBO', 'PH', 'Asia/Chongqing'),
('KMG', 'KUNMING', 'CN', ''),
('KMI', 'MIYAZAKI', 'JP', ''),
('KMQ', 'KOMATSU', 'JP', ''),
('KMU', 'KISIMAYU', 'SO', ''),
('KNO', 'MEDAN', 'ID', ''),
('KNU', 'KANPUR', 'IN', ''),
('KNX', 'KUNUNURRA', 'AU', 'Asia/Chongqing'),
('KOG', 'KOGO', 'GQ', 'Africa/Algiers'),
('KOJ', 'KAGOSHIMA', 'JP', ''),
('KOS', 'SIHANOUKVILLE', 'KH', 'Asia/Bangkok'),
('KQH', 'AJMER', 'IN', ''),
('KRA', 'KRASNOYARSK', 'RU', ''),
('KRR', 'KRASNODAR', 'RU', ''),
('KRT', 'KHARTOUM', 'SD', ''),
('KTA', 'KARRATHA', 'AU', 'Asia/Chongqing'),
('KTM', 'KATHMANDU', 'NP', 'Asia/Almaty'),
('KTW', 'OZAROWICE', 'PL', ''),
('KUA', 'KUANTAN', 'MY', ''),
('KUL', 'KUALA LUMPUR', 'MY', ''),
('KUU', 'KULLU', 'IN', ''),
('KVA', 'KAVALA', 'GR', ''),
('KWE', 'GUIYANG', 'CN', 'Asia/Chongqing'),
('LAD', 'LUANDA', 'AO', 'America/Scoresbysund'),
('LAE', 'LAE', 'PG', 'Asia/Vladivostok'),
('LAO', 'LAOAG', 'PH', 'Asia/Chongqing'),
('LAQ', 'BAYDA', 'LY', ''),
('LAS', 'LAS VEGAS', 'US', ''),
('LAX', 'LOS ANGELES', 'US', ''),
('LBV', 'LIBREVILLE', 'GA', 'Africa/Algiers'),
('LCA', 'LARNARCA', 'CY', ''),
('LED', 'ST.PETERSBURG', 'RU', ''),
('LFW', 'LOME', 'TG', 'Africa/Casablanca'),
('LGK', 'LANGKAWI', 'MY', ''),
('LGP', 'LEGAZPI', 'PH', 'Asia/Chongqing'),
('LHE', 'LAHORE', 'PK', 'Asia/Aqtobe'),
('LHR', 'LONDON', 'GB', ''),
('LHW', 'LANZHOU', 'CN', 'Asia/Chongqing'),
('LKO', 'LUCKNOW', 'IN', ''),
('LLC', 'CAGAYAN', 'PH', ''),
('LLO', 'CAGAYAN NORTH', 'PH', ''),
('LNV', 'LIHIR ISLAND', 'PG', 'Asia/Vladivostok'),
('LON', 'LONDON', 'GB', 'Africa/Algiers'),
('LOP', 'MATARAM', 'ID', ''),
('LOS', 'LAGOS', 'NG', 'Africa/Algiers'),
('LPB', 'LAPAZ', 'BO', 'America/Araguaina'),
('LPQ', 'LUANG PRABANG', 'LA', ''),
('LST', 'LAUNCESTON', 'AU', ''),
('LTI', 'ALTAI', 'MN', 'Asia/Chongqing'),
('LTN', 'LUTON', 'GB', 'Africa/Casablanca'),
('LUH', 'LUDHIANA', 'IN', ''),
('LUX', 'LUXEMBOURG', 'LU', 'Africa/Cairo'),
('LXR', 'LUXOR', 'EG', ''),
('LXS', 'LIMNOS ISLAND', 'GE', ''),
('LYP', 'FAISALABAD', 'PK', 'Asia/Aqtobe'),
('MAA', 'CHENNAI', 'IN', ''),
('MAG', 'MADANG', 'PG', 'Asia/Vladivostok'),
('MAN', 'MANCHESTER', 'GB', ''),
('MBA', 'MOMBASA KENYA', 'KE', ''),
('MBT', 'MASBATE', 'PH', 'Asia/Chongqing'),
('MCT', 'MUSCAT', 'OM', ''),
('MCY', 'MAROOCHYDORE', 'AU', ''),
('MCZ', 'MACEIO', 'BR', ''),
('MDA', 'MUNDRA', 'IN', ''),
('MDL', 'MANDALAY', 'MM', ''),
('MED', 'MADINAH', 'SA', 'Africa/Djibouti'),
('MEL', 'MELBOURNE', 'AU', 'Asia/Vladivostok'),
('MES', 'MEDAN', 'ID', 'Asia/Bangkok'),
('MFM', 'MACAU', 'MO', ''),
('MGM', 'MONGOMEYEN', 'GQ', 'Africa/Algiers'),
('MGQ', 'MOGADISHU', 'SO', 'Africa/Djibouti'),
('MHD', 'MASHAD', 'IR', 'Asia/Tehran'),
('MIA', 'MIAMI', 'US', 'America/Bogota'),
('MJK', 'MONKEY MIA', 'AU', 'Asia/Chongqing'),
('MJT', 'MYTILENE', 'GR', ''),
('MKZ', 'MALLACA', 'MY', 'Asia/Bangkok'),
('MLE', 'MALE', 'MV', ''),
('MLG', 'MALANG', 'ID', 'Asia/Bangkok'),
('MMJ', 'MATSUMOTO', 'JP', 'Asia/Jayapura'),
('MMR', 'MYANMAR', 'MM', ''),
('MMX', 'MALMO', 'SE', 'Africa/Algiers'),
('MNL', 'MANILA', 'PH', 'Asia/Chongqing'),
('MOW', 'MOSCOW', 'RU', 'Africa/Djibouti'),
('MPH', 'CATICLAN', 'PH', 'Asia/Chongqing'),
('MRA', 'MISRATA', 'LY', ''),
('MRQ', 'MARINDUQUE', 'PH', 'Asia/Chongqing'),
('MUC', 'MUNICH', 'DE', ''),
('MUX', 'MULTAN', 'PK', 'Asia/Aqtobe'),
('MWK', 'MATAK', 'ID', 'Asia/Bangkok'),
('MWX', 'MUAN', 'KR', ''),
('MWZ', 'MWANZA', 'TZ', 'Africa/Djibouti'),
('MXP', 'MILAN', 'IT', 'Africa/Algiers'),
('MXV', 'MORON', 'MN', 'Asia/Chongqing'),
('MXW', 'MANDALGOBI', 'MN', 'Asia/Chongqing'),
('MYJ', 'MATSUYAMA', 'JP', ''),
('MYQ', 'MYSORE', 'IN', ''),
('MYW', 'MTWARA', 'TZ', 'Africa/Djibouti'),
('MYY', 'MIRI', 'MY', ''),
('MZR', 'MAZAR I SHARIF', 'AF', 'Asia/Kabul'),
('NAG', 'NAGPUR', 'IN', ''),
('NAT', 'NATAL', 'BR', ''),
('NBO', 'NAIROBI', 'KE', ''),
('NDE', 'MANDERA', 'KE', ''),
('NDJ', 'N''DJAMENA', 'TD', ''),
('NEU', 'SAM NEUA', 'LA', ''),
('NFO', 'NIAUFOOU', 'TO', 'Etc/GMT-13'),
('NGB', 'NINGBO', 'CN', 'Asia/Chongqing'),
('NGO', 'TOKONAME', 'JP', ''),
('NIM', 'NIAMEY', 'NE', 'Africa/Algiers'),
('NJF', 'NAJAF', 'IQ', 'Africa/Djibouti'),
('NKG', 'NANJING', 'CN', 'Asia/Chongqing'),
('NMB', 'DAMAN', 'IN', ''),
('NNG', 'NANNING', 'CN', 'Asia/Chongqing'),
('NNS', 'PITHORAGARH', 'IN', ''),
('NSK', 'NORILSK', 'RU', ''),
('NST', 'NAKHON SI THAMMARAT', 'TH', ''),
('NUE', 'NUREMBERG', 'DE', ''),
('ODY', 'OUDOMSAY', 'LA', ''),
('OGZ', 'VLADIKAVKAZ', 'RU', 'Asia/Aqtau'),
('OKA', 'NAHA', 'JP', 'Asia/Jayapura'),
('OKJ', 'OKAYAMA', 'JP', ''),
('OMC', 'ORMOC', 'PH', 'Asia/Chongqing'),
('OOL', 'GOLD COAST', 'AU', ''),
('ORY', 'PARIS', 'FR', 'Africa/Algiers'),
('OSA', 'OSAKA', 'JP', ''),
('OSS', 'OSH', 'KG', ''),
('OTP', 'BUCHAREST', 'RO', ''),
('OUA', 'OUAGADOUGOU', 'BF', 'Africa/Casablanca'),
('OVB', 'NOVOSIBIRSK', 'RU', ''),
('PAB', 'BILASPUR', 'IN', ''),
('PAP', 'PORT AU PRINCE', 'HT', 'America/Bogota'),
('PAT', 'PATNA', 'IN', ''),
('PBH', 'PARO', 'BT', 'Asia/Almaty'),
('PBO', 'PARABURDOO', 'AU', 'Asia/Chongqing'),
('PCQ', 'PHONGSALY', 'LA', ''),
('PEK', 'BEIJING', 'CN', 'Asia/Chongqing'),
('PEN', 'PENANG', 'MY', 'Asia/Chongqing'),
('PER', 'PERTH', 'AU', 'Asia/Chongqing'),
('PEW', 'PESHAWAR', 'PK', 'Asia/Aqtobe'),
('PGH', 'PANTNAGAR', 'IN', ''),
('PHC', 'PORT HARCOURT', 'NG', 'Africa/Algiers'),
('PHE', 'PORT HEDLAND', 'AU', 'Asia/Chongqing'),
('PHS', 'PHITSANULOK', 'TH', ''),
('PKU', 'PEKANBARU', 'ID', 'Asia/Bangkok'),
('PKZ', 'PAKSE', 'LA', ''),
('PLQ', 'PALANGA', 'LT', ''),
('PNH', 'PHNOM PENH', 'KH', 'Asia/Bangkok'),
('PNP', 'POPONDETTA', 'PG', 'Asia/Vladivostok'),
('PNQ', 'PUNE', 'IN', ''),
('PNR', 'POINTE NOIRE', 'CG', 'Africa/Algiers'),
('POA', 'PORTO ALEGRE', 'BR', ''),
('POM', 'PORT MORESBY', 'PG', 'Asia/Vladivostok'),
('PPS', 'PUERTO PRINCESA', 'PH', 'Asia/Chongqing'),
('PRG', 'PRAGUE', 'CZ', ''),
('PUS', 'BUSAN', 'KR', 'Asia/Jayapura'),
('PVG', 'SHANGHAI', 'CN', 'Asia/Chongqing'),
('PYB', 'JEYPORE', 'IN', ''),
('PYX', 'PATTAYA', 'TH', 'Asia/Bangkok'),
('QAH', 'HINDON', 'IN', ''),
('QBM', 'RANGEILUNDA', 'IN', ''),
('QUB', 'UBARI', 'LY', ''),
('RAB', 'RABAUL', 'PG', 'Asia/Vladivostok'),
('RAJ', 'RAJKOT', 'IN', ''),
('RBE', 'RATTANAKIRI', 'TH', 'Asia/Bangkok'),
('REC', 'RECIFE', 'BR', ''),
('REP', 'SIAM REAP', 'KH', 'Asia/Bangkok'),
('REW', 'REWA', 'IN', ''),
('RGN', 'YANGON', 'MM', 'Asia/Rangoon'),
('RHO', 'RODES ISLAND', 'GR', ''),
('RIX', 'RIGA', 'LV', ''),
('RIY', 'RIYAD MUKALLA', 'YE', 'Africa/Djibouti'),
('RMQ', 'TAICHUNG', 'TW', ''),
('ROR', 'KOROR', 'PH', 'Asia/Chongqing'),
('RPR', 'RAIPUR', 'IN', ''),
('RQY', 'SHIVAMOGGA', 'IN', ''),
('RRK', 'ROURKELA', 'IN', ''),
('RUH', 'RIYADH', 'SA', ''),
('RUP', 'RUPSI', 'IN', ''),
('RZR', 'RAMSAR', 'IR', 'Asia/Tehran'),
('SAG', 'MAHARASHTRA', 'IN', ''),
('SAH', 'SANAA', 'YE', 'Africa/Djibouti'),
('SAW', 'ISTAMBUL', 'TR', 'Africa/Djibouti'),
('SCO', 'AKTAU', 'KZ', 'Asia/Aqtobe'),
('SDJ', 'SENDAI', 'JP', ''),
('SDK', 'SANDAKAN', 'PH', 'Asia/Chongqing'),
('SDW', 'SINDHUDURG', 'IN', ''),
('SEB', 'SABHA', 'LY', ''),
('SEL', 'SEOUL', 'KR', 'Asia/Jayapura'),
('SEZ', 'MAHE ISLAND', 'SC', ''),
('SFB', 'SANFORD', 'US', 'America/Bogota'),
('SFE', 'SAN FERNANDO', 'PH', 'Asia/Chongqing'),
('SFO', 'SAN FRANCISCO', 'US', ''),
('SGC', 'SURGUT', 'RU', ''),
('SGN', 'HO CHI MINH', 'VN', 'Asia/Bangkok'),
('SHA', 'SHANGHAI', 'CN', ''),
('SHE', 'SHENYANG', 'CN', 'Asia/Chongqing'),
('SHJ', 'SHARJAH', 'AE', 'Asia/Kabul'),
('SHL', 'SHILLONG', 'IN', ''),
('SIN', 'SINGAPORE', 'SG', 'Asia/Chongqing'),
('SIQ', 'SINGKEP', 'ID', 'Asia/Bangkok'),
('SJI', 'SAN JOSE OCC MINDORO', 'PH', 'Asia/Chongqing'),
('SJW', 'SHIJIAZHUANG', 'CN', 'Asia/Chongqing'),
('SKG', 'THESSALONIKI', 'GR', ''),
('SKO', 'SAKOTO', 'NG', ''),
('SLV', 'SHIMLA', 'IN', ''),
('SMB', 'SUKABUMII', 'ID', ''),
('SMI', 'SAMOS ISLAND', 'GR', ''),
('SMQ', 'SAMPIT', 'ID', ''),
('SOC', 'SOLO', 'ID', 'Asia/Bangkok'),
('SOF', 'SOFIA', 'BG', ''),
('SOQ', 'SORONG', 'ID', 'Asia/Jayapura'),
('SOS', 'SIARGAO SAYAK', 'PH', 'Asia/Chongqing'),
('SRY', 'SARY', 'IR', 'Asia/Tehran'),
('SSA', 'SALVADOR DA BAHIA', 'BR', ''),
('SSG', 'MALABO', 'GQ', 'Africa/Algiers'),
('SSH', 'SHARM EL-SHEIKH', 'EG', 'Africa/Cairo'),
('STR', 'STUTTGART', 'DE', ''),
('STV', 'SURAT', 'IN', ''),
('SUB', 'SURABAYA', 'ID', 'Asia/Bangkok'),
('SUG', 'SURIGAO', 'PH', 'Asia/Chongqing'),
('SVK', 'BRATISLAVA', 'SK', ''),
('SVO', 'MOSKOW', 'RU', 'Africa/Djibouti'),
('SVX', 'EKATERINBURG', 'RU', 'Asia/Aqtobe'),
('SWA', 'SHANTOU', 'CN', 'Asia/Chongqing'),
('SWL', 'SAN VICENTE', 'PH', ''),
('SXR', 'SRINAGAR', 'ID', ''),
('SXV', 'SALEM', 'IN', ''),
('SYD', 'SYDNEY', 'AU', ''),
('SYZ', 'SHIRAZ', 'IR', 'Asia/Tehran'),
('SZX', 'SHENZHEN', 'CN', ''),
('TAC', 'TACLOBAN', 'PH', 'Asia/Chongqing'),
('TAE', 'DAEGU', 'KR', 'Asia/Jayapura'),
('TAG', 'TAGBILARAN', 'PH', 'Asia/Chongqing'),
('TAI', 'TAIZ', 'YE', 'Africa/Djibouti'),
('TAK', 'TAKAMATSU', 'JP', 'Asia/Jayapura'),
('TAO', 'QINGDAO', 'CN', 'Asia/Chongqing'),
('TAS', 'TASHKENT', 'UZ', ''),
('TBH', 'TABLAS', 'PH', 'Asia/Chongqing'),
('TBS', 'TBILISI', 'GE', 'Asia/Aqtau'),
('TBU', 'NUKUALOFA', 'TO', 'Etc/GMT-13'),
('TDG', 'TANDAG', 'PH', 'Asia/Chongqing'),
('TEI', 'TEZU', 'IN', ''),
('TEZ', 'TEZPUR', 'IN', ''),
('THR', 'TEHRAN', 'IR', 'Asia/Tehran'),
('TII', 'TIRINKOT', 'AF', 'Asia/Kabul'),
('TIM', 'TIMIKA', 'ID', 'Asia/Jayapura'),
('TIP', 'TRIPOLI', 'LY', ''),
('TIR', 'TIRUPATI', 'IN', ''),
('TKG', 'LAMPUNG', 'ID', 'Asia/Bangkok'),
('TLV', 'TEL AVIV', 'IL', ''),
('TMS', 'SAO TOME IS', 'ST', 'Africa/Casablanca'),
('TNA', 'JINAN', 'CN', 'Asia/Chongqing'),
('TNI', 'SATNA', 'IN', ''),
('TNJ', 'TANJUNG PINANG', 'ID', 'Asia/Bangkok'),
('TNZ', 'TOSONTSENGEL', 'MN', 'Asia/Chongqing'),
('TOB', 'TOBRUK', 'LY', ''),
('TOY', 'TOYAMA', 'JP', ''),
('TPE', 'TAIPEI', 'TW', 'Asia/Chongqing'),
('TRK', 'TARAKAN', 'ID', 'Asia/Chongqing'),
('TRV', 'THIRUVANANTHAPURAM', 'IN', ''),
('TRZ', 'TIRUCHIRAPALLI', 'IN', ''),
('TSE', 'ASTANA', 'KZ', 'Asia/Almaty'),
('TSN', 'TIANJIN', 'CN', 'Asia/Chongqing'),
('TSZ', 'TSETSERLEG', 'MN', 'Asia/Chongqing'),
('TUG', 'TUGUEGARAO', 'PH', ''),
('TUN', 'TUNIS', 'TN', ''),
('TWT', 'TAWITAWI', 'PH', 'Asia/Chongqing'),
('TXL', 'BERLIN', 'DE', ''),
('TYN', 'TAIYUAN', 'CN', ''),
('TYO', 'TOKYO', 'JP', 'Asia/Jayapura'),
('TZL', 'TUZLA', 'BA', ''),
('UBJ', 'UBE', 'JP', ''),
('UBP', 'UBON RATCHATHANI', 'TH', ''),
('UDR', 'UDAIPUR', 'IN', ''),
('UET', 'QUEETA', 'PK', 'Asia/Aqtobe'),
('UGA', 'BULGAN', 'MN', 'Asia/Chongqing'),
('UGT', 'UMNUGOBITOUR', 'MN', 'Asia/Chongqing'),
('UIH', 'QUI NHON', 'VN', ''),
('UJN', 'UJJAIN', 'IN', ''),
('UKE', 'UTKELA', 'IN', ''),
('ULG', 'ULGII', 'MN', 'Asia/Chongqing'),
('ULN', 'ULAANBAATAR', 'MN', 'Asia/Chongqing'),
('ULO', 'ULAANGOM', 'MN', 'Asia/Chongqing'),
('ULZ', 'DONOI', 'MN', 'Asia/Chongqing'),
('UNR', 'UNDERKHAAN', 'MN', 'Asia/Chongqing'),
('UPG', 'MAKASSAR', 'ID', 'Asia/Chongqing'),
('URA', 'URALSK', 'KZ', 'Asia/Aqtau'),
('URC', 'URUMQI', 'CN', 'Asia/Chongqing'),
('URT', 'SURAT THANI', 'TH', 'Asia/Bangkok'),
('USM', 'KO SAMUI ISLAND', 'TH', ''),
('USU', 'BUSUANGA', 'PH', 'Asia/Chongqing'),
('UTH', 'UDON THANI', 'TH', 'Asia/Bangkok'),
('UTP', 'UTAPAO', 'TH', 'Asia/Bangkok'),
('UUN', 'BARUUN-URT', 'MN', 'Asia/Chongqing'),
('VAI', 'VANIMO', 'PG', 'Asia/Vladivostok'),
('VAV', 'VAVAU', 'TO', 'Etc/GMT-13'),
('VCA', 'CAN THO', 'VN', ''),
('VDX', 'GHAZIABAD', 'IN', ''),
('VDY', 'TORANAGALLU', 'IN', ''),
('VGA', 'VIJAYWADA', 'IN', ''),
('VIE', 'VIENNA', 'AT', 'Africa/Algiers'),
('VKO', 'MOSKOW', 'RU', 'Africa/Djibouti'),
('VNO', 'VILNIUS', 'LT', ''),
('VNS', 'VARANASI', 'IN', ''),
('VRC', 'VIRAC', 'PH', 'Asia/Chongqing'),
('VTE', 'VIENTIANE', 'LA', ''),
('VTZ', 'VISAKHAPATNAM', 'IN', ''),
('VVI', 'SANTA CRUZ', 'BO', 'America/Araguaina'),
('WAW', 'WARSAW', 'PL', ''),
('WJR', 'WAJIR', 'KE', ''),
('WNP', 'NAGA', 'PH', 'Asia/Chongqing'),
('WNZ', 'WENZHOU', 'CN', ''),
('WUH', 'WUHAN TIANHE', 'CN', 'Asia/Chongqing'),
('WUU', 'WAU', 'SS', ''),
('WUX', 'WUXI', 'CN', ''),
('WWK', 'WEWAK', 'PG', 'Asia/Vladivostok'),
('WXN', 'WANXIAN', 'CN', ''),
('XIY', 'XI AN', 'CN', 'Asia/Chongqing'),
('XKH', 'XIENG KHOUANG', 'LA', ''),
('XMN', 'XIAMEN', 'CN', 'Asia/Chongqing'),
('XQU', 'QUALICUM', 'CA', 'America/Dawson'),
('XXX', 'XXX', 'PH', ''),
('YAO', 'YAOUNDE', 'CM', 'Africa/Algiers'),
('YAT', 'ATTAWAPISKAT', 'CA', ''),
('YDT', 'VANCOUVER', 'CA', 'America/Dawson'),
('YFA', 'FORT ALBANY', 'CA', ''),
('YGB', 'GILLIES BAY', 'CA', 'America/Dawson'),
('YGJ', 'MIHO YONAGO', 'JP', ''),
('YGW', 'WHAPMAGOOSTUI', 'CA', ''),
('YIH', 'YICHANG', 'CN', ''),
('YKQ', 'WASKAGANISH', 'CA', ''),
('YKU', 'CHISASIBI', 'CA', ''),
('YMO', 'MOOSONEE', 'CA', ''),
('YMT', 'CHIBOUGAMAU', 'CA', ''),
('YNC', 'WEMINDJI', 'CA', ''),
('YNS', 'NEMISCAU', 'CA', ''),
('YPB', 'PORT ALBERNI', 'CA', 'America/Dawson'),
('YPO', 'PEAWANUCK', 'CA', ''),
('YTS', 'TIMMINS', 'CA', ''),
('YUL', 'MONTREAL', 'CA', ''),
('YUY', 'ROUYN-NORANDA', 'CA', ''),
('YVO', 'VAL DOR', 'CA', ''),
('YVR', 'VANCOUVER', 'CA', 'America/Dawson'),
('ZAJ', 'ZARANJ', 'AF', 'Asia/Kabul'),
('ZAM', 'ZAMBOANGA CITY', 'PH', 'Asia/Chongqing'),
('ZEM', 'EASTMAIN RIVER', 'CA', ''),
('ZER', 'ZIRO', 'IN', ''),
('ZKE', 'KASHECHEWAN', 'CA', ''),
('ZNE', 'NEWMAN', 'AU', 'Asia/Chongqing'),
('ZNZ', 'KISAUNI', 'TZ', 'Africa/Djibouti'),
('ZRH', 'ZURICH', 'CH', '');
