DROP TABLE IF EXISTS countries;
CREATE TABLE IF NOT EXISTS countries(
    code_2          CHAR(2) PRIMARY KEY,
    code_3          CHAR(3),
    name            TEXT,
    ccy             CHAR(3),
    phone_code      VARCHAR(10),
    status          INT DEFAULT 1
);

INSERT INTO countries (code_2, code_3, name, ccy, phone_code) VALUES
('AD', 'AND', 'ANDORRA', 'EUR', '376'),
('AE', 'ARE', 'UNITED ARAB EMIRATES', 'AED', '971'),
('AF', 'AFG', 'AFGHANISTAN', 'AFN', '93'),
('AG', 'ATG', 'ANTIGUA AND BARBUDA', 'XCD', '1268'),
('AI', 'AIA', 'ANGUILLA', 'XCD', '1264'),
('AL', 'ALB', 'ALBANIA', 'ALL', '355'),
('AM', 'ARM', 'ARMENIA', 'AMD', '374'),
('AO', 'AGO', 'ANGOLA', 'AOA', '244'),
('AQ', 'ATA', 'ANTARCTICA', 'NOK', '672'),
('AR', 'ARG', 'ARGENTINA', 'ARS', '54'),
('AS', 'ASM', 'AMERICAN SAMOA', 'USD', '1684'),
('AT', 'AUT', 'AUSTRIA', 'EUR', '43'),
('AU', 'AUS', 'AUSTRALIA', 'AUD', '61'),
('AW', 'ABW', 'ARUBA', 'AWG', '297'),
('AX', 'ALA', 'ALAND ISLANDS', 'EUR', ''),
('AZ', 'AZE', 'AZERBAIJAN', 'AZN', '994'),
('BA', 'BIH', 'BOSNIA AND HERZEGOVINA', 'BAM', '387'),
('BB', 'BRB', 'BARBADOS', 'BBD', '1246'),
('BD', 'BGD', 'BANGLADESH', 'BDT', '880'),
('BE', 'BEL', 'BELGIUM', 'EUR', '32'),
('BF', 'BFA', 'BURKINA FASO', 'XOF', '226'),
('BG', 'BGR', 'BULGARIA', 'BGN', '359'),
('BH', 'BHR', 'BAHRAIN', 'BHD', '973'),
('BI', 'BDI', 'BURUNDI', 'BIF', '257'),
('BJ', 'BEN', 'BENIN', 'XOF', '229'),
('BL', 'BLM', 'SAINT BARTH�EMY', 'EUR', '590'),
('BM', 'BMU', 'BERMUDA', 'BMD', '1441'),
('BN', 'BRN', 'BRUNEI DARUSSALAM', '', '673'),
('BO', 'BOL', 'BOLIVIA', 'USD', '591'),
('BQ', 'BES', 'BONAIRE', 'USD', ''),
('BR', 'BRA', 'BRAZIL', 'BRL', '55'),
('BS', 'BHS', 'BAHAMAS', 'BSD', '1242'),
('BT', 'BTN', 'BHUTAN', 'BTN', '975'),
('BV', 'BVT', 'BOUVET ISLAND', 'NOK', ''),
('BW', 'BWA', 'BOTSWANA', 'BWP', '267'),
('BY', 'BLR', 'BELARUS', 'BYR', '375'),
('BZ', 'BLZ', 'BELIZE', 'BZD', '501'),
('CA', 'CAN', 'CANADA', 'CAD', '1'),
('CC', 'CCK', 'COCOS (KEELING) ISLANDS', 'AUD', '61'),
('CD', 'COD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CDF', '243'),
('CF', 'CAF', 'CENTRAL AFRICAN REPUBLIC', 'XAF', '236'),
('CG', 'COG', 'CONGO', 'XAF', '242'),
('CH', 'CHE', 'SWITZERLAND', 'CHF', '41'),
('CI', 'CIV', 'IVORY COAST', 'XOF', '225'),
('CK', 'COK', 'COOK ISLANDS', 'NZD', '682'),
('CL', 'CHL', 'CHILE', 'CLP', '56'),
('CM', 'CMR', 'CAMEROON', 'XAF', '237'),
('CN', 'CHN', 'CHINA', 'CNY', '86'),
('CO', 'COL', 'COLOMBIA', 'COP', '57'),
('CR', 'CRI', 'COSTA RICA', 'CRC', '506'),
('CU', 'CUB', 'CUBA', 'CUP', '53'),
('CV', 'CPV', 'CAPE VERDE', 'CVE', '238'),
('CW', 'CUW', 'CURACAO', 'ANG', '599'),
('CX', 'CXR', 'CHRISTMAS ISLAND', 'AUD', '61'),
('CY', 'CYP', 'CYPRUS', 'EUR', '357'),
('CZ', 'CZE', 'CZECH REPUBLIC', 'CZK', '420'),
('DE', 'DEU', 'GERMANY', 'EUR', '49'),
('DJ', 'DJI', 'DJIBOUTI', 'DJF', '253'),
('DK', 'DNK', 'DENMARK', 'DKK', '45'),
('DM', 'DMA', 'DOMINICA', 'XCD', '1767'),
('DO', 'DOM', 'DOMINICAN REPUBLIC', 'DOP', '1809'),
('DZ', 'DZA', 'ALGERIA', 'DZD', '213'),
('EC', 'ECU', 'ECUADOR', 'USD', '593'),
('EE', 'EST', 'ESTONIA', 'EUR', '372'),
('EG', 'EGY', 'EGYPT', 'EGP', '20'),
('EH', 'ESH', 'WESTERN SAHARA', 'DZD', '212'),
('ER', 'ERI', 'ERITREA', 'ERN', '291'),
('ES', 'ESP', 'SPAIN', 'EUR', '34'),
('ET', 'ETH', 'ETHIOPIA', 'ETB', '251'),
('FI', 'FIN', 'FINLAND', 'EUR', '358'),
('FJ', 'FJI', 'FIJI', 'FJD', '679'),
('FK', 'FLK', 'FALKLAND ISLAND', 'FKP', '500'),
('FM', 'FSM', 'MICRONESIA', 'USD', '691'),
('FO', 'FRO', 'FAROE ISLANDS', 'DKK', '298'),
('FR', 'FRA', 'FRANCE', 'EUR', '33'),
('GA', 'GAB', 'GABON', 'XAF', '241'),
('GB', 'GBR', 'UNITED KINGDOM', 'GBP', '44'),
('GD', 'GRD', 'GRENADA', 'XCD', '1473'),
('GE', 'GEO', 'GEORGIA', 'GEL', '995'),
('GF', 'GUF', 'FRENCH GUIANA', 'EUR', ''),
('GG', 'GGY', 'GUERNSEY', 'GBP', '441481'),
('GH', 'GHA', 'GHANA', 'GHS', '233'),
('GI', 'GIB', 'GIBRALTAR', 'GIP', '350'),
('GL', 'GRL', 'GREENLAND', 'DKK', '299'),
('GM', 'GMB', 'GAMBIA', 'GMD', '220'),
('GN', 'GIN', 'GUINEA', 'GNF', '224'),
('GP', 'GLP', 'GUADELOUPE', 'EUR', ''),
('GQ', 'GNQ', 'EQUATORIAL GUINEA', 'XAF', '240'),
('GR', 'GRC', 'GREECE', 'EUR', '30'),
('GS', 'SGS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GBP', ''),
('GT', 'GTM', 'GUATEMALA', 'GTQ', '502'),
('GU', 'GUM', 'GUAM', 'USD', '1671'),
('GW', 'GNB', 'GUINEA-BISSAU', 'XOF', '245'),
('GY', 'GUY', 'GUYANA', 'GYD', '592'),
('HK', 'HKG', 'HONG KONG', 'HKD', '852'),
('HM', 'HMD', 'HEARD ISLAND AND MCDONALD ISLANDS', 'AUD', ''),
('HN', 'HND', 'HONDURAS', 'HNL', '504'),
('HR', 'HRV', 'CROATIA', 'HRK', '385'),
('HT', 'HTI', 'HAITI', 'USD', '509'),
('HU', 'HUN', 'HUNGARY', 'EUR', '36'),
('IC', 'IOT', 'BRITISH INDIAN OCEAN TERRITORY', 'USD', ''),
('ID', 'IDN', 'INDONESIA', 'IDR', '62'),
('IE', 'IRL', 'IRELAND', 'EUR', '353'),
('IL', 'ISR', 'ISRAEL', 'ILS', '972'),
('IM', 'IMN', 'ISLE OF MAN', 'GBP', '441624'),
('IN', 'IND', 'INDIA', 'INR', '91'),
('IO', 'IOT', 'BRITISH INDIAN OCEAN TERRITORY', 'GBP', '246'),
('IQ', 'IRQ', 'IRAQ', 'IQD', '964'),
('IR', 'IRN', 'IRAN', 'IRR', '98'),
('IS', 'ISL', 'ICELAND', 'ISK', '354'),
('IT', 'ITA', 'ITALY', 'EUR', '39'),
('JE', 'JEY', 'JERSEY', 'GBP', '441534'),
('JM', 'JAM', 'JAMAICA', 'JMD', '1876'),
('JO', 'JOR', 'JORDAN', 'JOD', '962'),
('JP', 'JPN', 'JAPAN', 'JPY', '81'),
('KE', 'KEN', 'KENYA', 'KES', '254'),
('KG', 'KGZ', 'KYRGYZSTAN', 'KGS', '996'),
('KH', 'KHM', 'CAMBODIA', 'USD', '855'),
('KI', 'KIR', 'KIRIBATI', 'AUD', '686'),
('KM', 'COM', 'COMOROS', 'KMF', '269'),
('KN', 'KNA', 'SAINT KITTS AND NEVIS', 'XCD', '1869'),
('KP', 'PRK', 'NORTH KOREA', 'KPW', '850'),
('KR', 'KOR', 'SOUTH KOREA', 'KRW', '82'),
('KW', 'KWT', 'KUWAIT', 'KWD', '965'),
('KY', 'CYM', 'CAYMAN ISLAND', 'KYD', '1345'),
('KZ', 'KAZ', 'KAZAKHSTAN', 'KZT', '7'),
('LA', 'LAO', 'LAOS', 'LAK', '856'),
('LB', 'LBN', 'LEBANON', '', '961'),
('LC', 'LCA', 'SAINT LUCIA', 'XCD', '1758'),
('LI', 'LIE', 'LIECHTENSTEIN', 'CHF', '423'),
('LK', 'LKA', 'SRI LANKA', 'LKR', '94'),
('LR', 'LBR', 'LIBERIA', 'LRD', '231'),
('LS', 'LSO', 'LESOTHO', 'LSL', '266'),
('LT', 'LTU', 'LITHUANIA', 'LTL', '370'),
('LU', 'LUX', 'LUXEMBOURG', 'EUR', '352'),
('LV', 'LVA', 'LATVIA', 'LVL', '371'),
('LY', 'LBY', 'LIBYA', 'LYD', '218'),
('MA', 'MAR', 'MOROCCO', 'MAD', '212'),
('MC', 'MCO', 'MONACO', 'EUR', '377'),
('MD', 'MDA', 'MOLDOVA', 'MDL', '373'),
('ME', 'MNE', 'MONTENEGRO', 'EUR', '382'),
('MF', 'MAF', 'SAINT MARTIN (FRENCH PART)', 'EUR', '590'),
('MG', 'MDG', 'MADAGASCAR', 'MGA', '261'),
('MH', 'MHL', 'MARSHALL ISLANDS', 'USD', '692'),
('MK', 'MKD', 'MACEDONIA', 'MKD', '389'),
('ML', 'MLI', 'MALI', 'XOF', '223'),
('MM', 'MMR', 'MYANMAR', 'MMK', '95'),
('MN', 'MNG', 'MONGOLIA', 'MNT', '976'),
('MO', 'MAC', 'MACAO', 'MOP', '853'),
('MP', 'MNP', 'NORTHERN MARIANA ISLANDS', 'USD', '1670'),
('MQ', 'MTQ', 'MARTINIQUE', 'EUR', ''),
('MR', 'MRT', 'MAURITANIA', 'MRO', '222'),
('MS', 'MSR', 'MONTSERRAT', 'XCD', '1664'),
('MT', 'MLT', 'MALTA', 'EUR', '356'),
('MU', 'MUS', 'MAURITIUS', 'MUR', '230'),
('MV', 'MDV', 'MALDIVES', 'MVR', '960'),
('MW', 'MWI', 'MALAWI', 'MWK', '265'),
('MX', 'MEX', 'MEXICO', 'MXN', '52'),
('MY', 'MYS', 'MALAYSIA', 'MYR', '60'),
('MZ', 'MOZ', 'MOZAMBIQUE', 'MZN', '258'),
('NA', 'NAM', 'NAMIBIA', 'NAD', '264'),
('NC', 'NCL', 'NEW CALEDONIA', 'XPF', '687'),
('NE', 'NER', 'NIGER', 'XOF', '227'),
('NF', 'NFK', 'NORFOLK ISLAND', 'AUD', ''),
('NG', 'NGA', 'NIGERIA', 'NGN', '234'),
('NI', 'NIC', 'NICARAGUA', 'NIO', '505'),
('NL', 'NLD', 'NETHERLANDS', 'EUR', '31'),
('NO', 'NOR', 'NORWAY', 'NOK', '47'),
('NP', 'NPL', 'NEPAL', 'NPR', '977'),
('NR', 'NRU', 'NAURU', 'AUD', '674'),
('NU', 'NIU', 'NIUE', 'NZD', '683'),
('NZ', 'NZL', 'NEW ZEALAND', 'NZD', '64'),
('OM', 'OMN', 'OMAN', 'OMR', '968'),
('PA', 'PAN', 'PANAMA', 'USD', '507'),
('PE', 'PER', 'PERU', 'PEN', '51'),
('PF', 'PYF', 'FRENCH POLYNESIA', 'XPF', '689'),
('PG', 'PNG', 'PAPUA NEW GUINEA', 'USD', '675'),
('PH', 'PHL', 'PHILIPPINES', 'PHP', '63'),
('PK', 'PAK', 'PAKISTAN', 'PKR', '92'),
('PL', 'POL', 'POLAND', 'PLN', '48'),
('PM', 'SPM', 'SAINT PIERRE AND MIQUELON', 'EUR', '508'),
('PN', 'PCN', 'PITCAIRN', 'NZD', '64'),
('PR', 'PRI', 'PUERTO RICO', 'USD', '1787'),
('PS', 'PSE', 'PALESTINIAN', 'JOD', '970'),
('PT', 'PRT', 'PORTUGAL', 'EUR', '351'),
('PW', 'PLW', 'PALAU', 'USD', '680'),
('PY', 'PRY', 'PARAGUAY', 'PYG', '595'),
('QA', 'QAT', 'QATAR', 'QAR', '974'),
('RE', 'REU', 'REUNION', 'EUR', '262'),
('RO', 'ROU', 'ROMANIA', '', '40'),
('RS', 'SRB', 'SERBIA', 'RSD', '381'),
('RU', 'RUS', 'RUSSIA', 'RUB', '7'),
('RW', 'RWA', 'RWANDA', 'RWF', '250'),
('SA', 'SAU', 'SAUDI ARABIA', 'SAR', '966'),
('SB', 'SLB', 'SOLOMON ISLANDS', 'SBD', '677'),
('SC', 'SYC', 'SEYCHELLES', 'SCR', '248'),
('SD', 'SDN', 'SUDAN', 'SDG', '249'),
('SE', 'SWE', 'SWEDEN', 'SEK', '46'),
('SG', 'SGP', 'SINGAPORE', 'SGD', '65'),
('SH', 'SHN', 'SAINT HELENA', 'SHP', '290'),
('SI', 'SVN', 'SLOVENIA', 'EUR', '386'),
('SJ', 'SJM', 'SVALBARD AND JAN MAYEN', 'NOK', '47'),
('SK', 'SVK', 'SLOVAKIA', 'EUR', '421'),
('SL', 'SLE', 'SIERRA LEONE', 'SLL', '232'),
('SM', 'SMR', 'SAN MARINO', 'EUR', '378'),
('SN', 'SEN', 'SENEGAL', 'XOF', '221'),
('SO', 'SOM', 'SOMALIA', 'SOS', '252'),
('SR', 'SUR', 'SURINAME', 'SRD', '597'),
('SS', 'SSD', 'SOUTH SUDAN', 'SSP', '211'),
('ST', 'STP', 'SAO TOME AND PRINCIPE', 'STD', '239'),
('SV', 'SLV', 'EL SALVADOR', 'USD', '503'),
('SX', 'SXM', 'SINT MAARTEN (DUTCH PART)', 'ANG', '1721'),
('SY', 'SYR', 'SYRIA', 'USD', '963'),
('SZ', 'SWZ', 'SWAZILAND', 'SZL', '268'),
('TC', 'TCA', 'TURKS AND CAICOS ISLANDS', 'USD', '1649'),
('TD', 'TCD', 'CHAD', 'XAF', '235'),
('TF', 'ATF', 'FRENCH SOUTHERN TERRITORIES', 'EUR', ''),
('TG', 'TGO', 'TOGO', 'XOF', '228'),
('TH', 'THA', 'THAILAND', 'THB', '66'),
('TJ', 'TJK', 'TAJIKISTAN', '', '992'),
('TK', 'TKL', 'TOKELAU', 'NZD', '690'),
('TM', 'TKM', 'TURKMENISTAN', 'TMT', '993'),
('TN', 'TUN', 'TUNISIA', 'TND', '216'),
('TO', 'TON', 'TONGA', 'TOP', '676'),
('TR', 'TUR', 'TURKEY', '', '90'),
('TS', 'TLS', 'TIMOR LESTE', 'USD', ''),
('TT', 'TTO', 'TRINIDAD AND TOBAGO', 'TTD', '1868'),
('TV', 'TUV', 'TUVALU', 'AUD', '688'),
('TW', 'TWN', 'TAIWAN', 'TWD', '886'),
('TZ', 'TZA', 'TANZANIA', '', '255'),
('UA', 'UKR', 'UKRAINE', 'UAH', '380'),
('UG', 'UGA', 'UGANDA', 'USD', '256'),
('UM', 'UMI', 'US MINOR OUTLYING', 'USD', ''),
('US', 'USA', 'UNITED STATES OF AMERICA', 'USD', '1'),
('UY', 'URY', 'URUGUAY', 'UYU', '598'),
('UZ', 'UZB', 'UZBEKISTAN', 'UZS', '998'),
('VA', 'VAT', 'HOLY SEE (VATICAN CITY STATE)', 'EUR', '379'),
('VC', 'VCT', 'SAINT VINCENT AND THE GRENADINES', 'XCD', '1784'),
('VE', 'VEN', 'VENEZUELA', 'VEF', '58'),
('VG', 'VGB', 'VIRGIN ISLANDS, BRITISH', 'USD', '1284'),
('VI', 'VIR', 'VIRGIN ISLANDS, U.S.', 'USD', '1340'),
('VN', 'VNM', 'VIETNAM', 'VND', '84'),
('VU', 'VUT', 'VANUATU', 'VUV', '678'),
('WF', 'WLF', 'WALLIS AND FUTUNA', 'XPF', '681'),
('WS', 'WSM', 'SAMOA', 'USD', '685'),
('YE', 'YEM', 'YEMEN', 'YER', '967'),
('YT', 'MYT', 'MAYOTTE', 'EUR', '262'),
('ZA', 'ZAF', 'SOUTH AFRICA', 'ZAR', '27'),
('ZM', 'ZMB', 'ZAMBIA', 'ZMW', '260'),
('ZW', 'ZWE', 'ZIMBABWE', 'ZWD', '263');
